refactor

diff --git a/eaws b/eaws
--- a/eaws
+++ b/eaws
@@ -335,12 +335,9 @@ inspect_args() {
 check_profile() {
 	if [ "${args[--profile]}" ];then
 		source assume ${args[--profile]}
-	elif [ "${AWS_PROFILE:-}" ]
+	elif ! [ "${AWS_PROFILE:-}" ]
 	then
-		source assume ${AWS_PROFILE:-}
-	else
-
-		source assume ${args[--profile]}
+		source assume
 	fi
 }
 
@@ -401,46 +398,43 @@ eaws_logs_view_command() {
 # :command.function
 eaws_container_list_command() {
   # src/container_list_command.sh
+  #!/usr/bin/env bash
   check_profile
 
   # Get cluster
   cluster=$(aws ecs list-clusters |jq -r '.clusterArns[]'| awk -F'/' '{print $2}'| fzf)
-
-  prof_clu="--cluster ${cluster}"
-
   # Get service
-  aws ecs list-services ${prof_clu} | jq '.serviceArns[]' | awk -F'/' '{print $3}'| sed 's/"//g' | awk 'NF'
+  aws ecs list-services --cluster ${cluster} | jq '.serviceArns[]' | awk -F'/' '{print $3}'| sed 's/"//g' | awk 'NF'
 
 }
 
 # :command.function
 eaws_container_connect_command() {
   # src/container_connect_command.sh
+  #!/usr/bin/env bash
   check_profile
 
   # Get cluster
   cluster=$(aws ecs list-clusters |jq -r '.clusterArns[]'| awk -F'/' '{print $2}'| fzf)
-
-  prof_clu="--cluster ${cluster}"
+  short_cluster="--cluster ${cluster}"
 
   # Get service
-  service=$(aws ecs list-services ${prof_clu} | jq '.serviceArns[]' | awk -F'/' '{print $3}'| sed 's/"//g' | awk 'NF' | fzf )
+  service=$(aws ecs list-services "${short_cluster}" | jq '.serviceArns[]' | awk -F'/' '{print $3}'| sed 's/"//g' | awk 'NF' | fzf )
 
   # Get task id
-  task=$(aws ecs list-tasks ${prof_clu} --service-name ${service} | jq '.taskArns[]'| sed 's/"//g'| fzf -1 )
+  task=$(aws ecs list-tasks "${short_cluster}" --service-name "${service}" | jq '.taskArns[]'| sed 's/"//g'| fzf -1 )
 
   # container
-  describe_container=$(aws ecs describe-tasks ${prof_clu} --tasks ${task})
+  describe_container=$(aws ecs describe-tasks "${short_cluster}" --tasks "${task}")
 
-  conteiner_instance_id=$( echo $describe_container | jq -r '.tasks[0].containerInstanceArn')
+  conteiner_instance_id=$( echo "$describe_container" | jq -r '.tasks[0].containerInstanceArn')
 
-  container_runtime_id=$( echo $describe_container | jq '.tasks[0].containers[] | "\(.name) \(.lastStatus) \(.healthStatus) \(.runtimeId)"' | fzf -1| awk '{print $NF}'| sed 's/"//g' )
+  container_runtime_id=$( echo "$describe_container" | jq '.tasks[0].containers[] | "\(.name) \(.lastStatus) \(.healthStatus) \(.runtimeId)"' | fzf -1| awk '{print $NF}'| sed 's/"//g' )
 
-  ec2_instance=$( aws ecs describe-container-instances ${prof_clu} --container-instances ${conteiner_instance_id} | jq -r '.containerInstances[0].ec2InstanceId' )
+  ec2_instance=$( aws ecs describe-container-instances "${short_cluster}" --container-instances "${conteiner_instance_id}" | jq -r '.containerInstances[0].ec2InstanceId' )
 
   # Get target ssm
   document_name="AWS-StartInteractiveCommand"
-  parameters_command="sudo docker exec -it ${container_runtime_id} sh"
 
   aws ssm start-session --target ${ec2_instance} --document-name ${document_name} --parameters command="sudo docker exec -ti ${container_runtime_id} sh"
 
@@ -497,6 +491,10 @@ parse_requirements() {
   fi
   if ! [[ -x "$(command -v fzf)" ]]; then
     printf "missing dependency: fzf\n" >&2
+    exit 1
+  fi
+  if ! [[ -x "$(command -v granted)" ]]; then
+    printf "missing dependency: granted\n" >&2
     exit 1
   fi
 
